exclude: ^(src/octoprint/vendor/|src/octoprint/static/js/lib|src/octoprint/static/vendor|tests/static/js/lib|tests/util/_files|docs/|scripts/|translations/|.*\.css|.*\.svg)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/OctoPrint/codemods
    rev: main
    hooks:
      - id: codemod_dict_to_literal
        args: ["--ignore", "src/octoprint/vendor"]
        stages: ["manual"]
      - id: codemod_set_to_literal
        args: ["--ignore", "src/octoprint/vendor"]
        stages: ["manual"]
      - id: codemod_not_in
        args: ["--ignore", "src/octoprint/vendor"]
        stages: ["manual"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.4
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: ["--config", "black.toml"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
  - repo: https://github.com/prettier/prettier
    rev: master
    hooks:
      - id: prettier
