name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let labels = [];
            context.payload.issue.labels.forEach(label => { labels.push(label.name) });

            if (context.payload.issue.title.match(/\[request\]|feature request/i)) {
              labels.push('request');
              labels = labels.filter(label => label !== 'triage');
            }
            if (context.payload.issue.title.match(/\[brainstorming\]/i)) {
              labels.push('brainstorming');
              labels = labels.filter(label => label !== 'triage');
            }
            if (context.payload.issue.title.match(/\[rc feedback\]/i)) {
              labels.push('rc feedback');
              labels = labels.filter(label => label !== 'triage');
            }

            if (labels.length === 0) {
              labels.push('triage');
            }

            github.issues.setLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labels
            })
